import logging

from sqlalchemy.ext.asyncio import AsyncSession

from src.applications.dto import RoutingResult, TaskPayload
from src.applications.models import Application
from src.applications.repository import ApplicationRepository
from src.core.cloud_tasks import (
    CloudTaskRetryableError,
    CloudTasksClient,
    CloudTaskTerminalError,
)
from src.core.enums import ApplicationStatus, ApplicationStrategy, TaskType
from src.jobs.models import Job

logger = logging.getLogger(__name__)


class TaskDispatcher:
    """
    Enqueues Cloud Tasks for each ApplicationStrategy determined by the router.
    Ensures idempotency using ApplicationRepository.
    """

    def __init__(self, session: AsyncSession, tasks_client: CloudTasksClient):
        self._session = session
        self._repo = ApplicationRepository(session)
        self._tasks_client = tasks_client

    async def dispatch(self, job: Job, routing_result: RoutingResult) -> None:
        """
        Processes a routing result for a job.
        Creates application records and dispatches tasks independently.
        """
        if routing_result.skipped:
            logger.info(f"Job {job.id} skipped based on routing result.")
            return

        if not routing_result.strategies:
            logger.info(f"No strategies matched for Job {job.id}. Skipping dispatch.")
            return

        for strategy in routing_result.strategies:
            try:
                await self._dispatch_strategy(job, strategy)
            except Exception as e:
                # Catch unexpected dispatcher-level exceptions so they don't halt other strategies
                logger.error(
                    f"Unexpected error dispatching {strategy} for Job {job.id}: {e.__class__.__name__}"
                )

    async def _dispatch_strategy(self, job: Job, strategy: ApplicationStrategy) -> None:
        """
        Dispatches a single strategy independently.
        """
        # Idempotency check: prevent duplicate dispatches
        exists = await self._repo.exists_for_job_and_strategy(job.id, strategy)
        if exists:
            logger.info(
                f"Application already exists for job {job.id} and strategy {strategy}. Skipping dispatch."
            )
            return

        # State management: Record dispatched attempt
        application = Application(
            job_id=job.id,
            strategy=strategy,
            status=ApplicationStatus.pending,
        )
        self._repo.add(application)

        # We must flush to ensure the Application ID (if generated by DB) is ready,
        # though we generate it via uuid4 default. We will flush to catch any DB issues early.
        await self._session.flush()

        task_type = self._map_strategy_to_task_type(strategy)
        payload = TaskPayload(
            job_id=job.id,
            task_type=task_type,
        )

        try:
            self._enqueue_task(strategy, payload)
        except CloudTaskRetryableError as e:
            logger.error(
                f"Retryable error dispatching task {task_type} for job {job.id}: {e}"
            )
            # The application status remains pending. It can be retried later.
        except CloudTaskTerminalError as e:
            logger.error(
                f"Terminal error dispatching task {task_type} for job {job.id}: {e}"
            )
            # Mark as dispatch_failed (ApplicationStatus.failed)
            application.status = ApplicationStatus.failed
            application.last_error = str(e)

    def _map_strategy_to_task_type(self, strategy: ApplicationStrategy) -> TaskType:
        mapping = {
            ApplicationStrategy.portal: TaskType.portal_application,
            ApplicationStrategy.form: TaskType.form_application,
            ApplicationStrategy.email: TaskType.email_application,
        }
        return mapping[strategy]

    def _enqueue_task(
        self, strategy: ApplicationStrategy, payload: TaskPayload
    ) -> None:
        """Calls the correct Cloud Tasks enqueue method."""
        if strategy == ApplicationStrategy.portal:
            self._tasks_client.enqueue_portal(payload)
        elif strategy == ApplicationStrategy.form:
            self._tasks_client.enqueue_form(payload)
        elif strategy == ApplicationStrategy.email:
            self._tasks_client.enqueue_email(payload)
        else:
            raise ValueError(f"Unsupported strategy for enqueueing: {strategy}")
